//export const rootEndpoint = "http://localhost:5001/api";
export const rootEndpoint = "http://10.0.2.2:5001/api"; // For Android localhost emulator debugging.
export const accountsEndpoint = rootEndpoint + "/accounts";
export const customerCartEndpoint = rootEndpoint + "/customerCartItems";
export const customerOrderStateDetailsEndpoint = rootEndpoint + "/customerOrderStateDetails";
export const customerOrderDetailsEndpoint = rootEndpoint + "/customerOrderDetails";
export const customerOrdersEndpoint = rootEndpoint + "/customerOrders";
export const customerProductDetailsEndpoint = rootEndpoint + "/customerProductDetails";
export const customersEndpoint = rootEndpoint + "/customers";
export const employeesEndpoint = rootEndpoint + "/employees";
export const productCategoriesEndpoint = rootEndpoint + "/productCategories";
export const productCollectionDetailsEndpoint = rootEndpoint + "/productCollectionDetails";
export const productCollectionEndpoint = rootEndpoint + "/productCollections";
export const productDetailsEndpoint = rootEndpoint + "/productDetails";
export const productsEndpoint = rootEndpoint + "/products";
export const emailsEndpoint = rootEndpoint + "/emails";